const test=require('node:test');
const assert=require('node:assert/strict');
const H=require('../src/hardware.js');
class Hub{
  constructor(){this.sent=[];this.cleared=[];this.panics=[];this.out=[{id:'out1',key:'acme|synth#1',name:'Synth',manufacturer:'Acme',state:'connected'},{id:'led1',key:'acme|pads#1',name:'Pads',manufacturer:'Acme',state:'connected'}];}
  outputDevices(){return this.out;}
  sendKey(key,data,timestamp=0){this.sent.push({key,data:[...data],timestamp});}
  clear(id){this.cleared.push(id);}
  panic(id,channels){this.panics.push({id,channels:[...channels]});}
}
const player=(id,source=id)=>({id,type:id,label:id,enabled:true,source});
const song={bpm:120,duration:4,rhythmOnly:false,tempoMap:[{time:0,bpm:120}],parts:[{id:'keys',name:'Keys',type:'keys',channel:1,notes:[{time:0,duration:.5,pitch:60,velocity:100},{time:1,duration:.25,pitch:64,velocity:90}]}],chordHighways:{}};
test('normalizes safe output settings',()=>{const s=H.normalizeSettings({clock:{enabled:1,transport:false,outputKey:'x'},players:{keys:{channel:99,feedback:'wat',feedbackNumber:-4}}});assert.equal(s.clock.enabled,true);assert.equal(s.clock.transport,false);assert.equal(s.players.keys.channel,16);assert.equal(s.players.keys.feedback,'off');assert.equal(s.players.keys.feedbackNumber,0);});
test('preset enables synth/feedback combinations',()=>{assert.deepEqual(H.applyPreset({channel:1},'synth').guide,true);assert.equal(H.applyPreset({channel:1},'feedback').feedback,'note');const h=H.applyPreset({channel:1},'hybrid');assert.equal(h.guide,true);assert.equal(h.feedback,'note');});
test('guide planner schedules note on/off on saved output key',()=>{const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.players.keys,{outputKey:'acme|synth#1',guide:true,channel:4});const e=new H.Engine({hub,settings,now:()=>1000});const plan=e.guidePlan(song,[player('keys')],0,2);assert.equal(plan.length,4);assert.deepEqual(plan[0].data,[0x93,60,100]);assert.deepEqual(plan[1].data,[0x83,60,0]);});
test('chord guide emits estimated chord tones instead of rhythm placeholders',()=>{const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.players.keys,{outputKey:'acme|synth#1',guide:true});const s={...song,rhythmOnly:true,chordHighways:{keys:[{time:0,duration:1,pitches:[60,64,67],pcs:[0,4,7],name:'C'}]}};const plan=new H.Engine({hub,settings}).guidePlan(s,[player('keys')],0,2);assert.equal(plan.length,6);assert.deepEqual(plan.slice(0,3).map(x=>x.data[1]),[60,64,67]);});
test('rhythm-only song without chords does not invent guide pitches',()=>{const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.players.keys,{outputKey:'acme|synth#1',guide:true});const s={...song,rhythmOnly:true};assert.equal(new H.Engine({hub,settings}).guidePlan(s,[player('keys')],0,2).length,0);});
test('feedback sends short note with grade velocity',()=>{let now=500;const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.players.drums,{outputKey:'acme|pads#1',channel:10,feedback:'note',feedbackNumber:42});const e=new H.Engine({hub,settings,now:()=>now});assert.equal(e.feedback(player('drums'),'great'),true);assert.deepEqual(hub.sent[0],{key:'acme|pads#1',data:[0x99,42,104],timestamp:500});assert.equal(hub.sent[1].timestamp,590);});
test('CC feedback pulses selected controller',()=>{const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.players.keys,{outputKey:'acme|pads#1',channel:3,feedback:'cc',feedbackNumber:7});new H.Engine({hub,settings,now:()=>10}).feedback(player('keys'),'perfect');assert.deepEqual(hub.sent.map(x=>x.data),[[0xb2,7,127],[0xb2,7,0]]);});
test('clock scheduler emits Start and 24 PPQN timestamps',()=>{let now=1000,songTime=-.1;const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.clock,{enabled:true,transport:true,outputKey:'acme|synth#1'});const e=new H.Engine({hub,settings,now:()=>now});e.start({song,players:[],speed:1,seek:0,end:1,resume:false,songNow:()=>songTime});assert.ok(hub.sent.some(x=>x.data[0]===0xfa));assert.ok(hub.sent.filter(x=>x.data[0]===0xf8).length>=1);e.stop();});
test('resume uses Continue instead of Start',()=>{const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.clock,{transport:true,outputKey:'acme|synth#1'});const e=new H.Engine({hub,settings,now:()=>1000});e.start({song,players:[],speed:1,seek:1,end:2,resume:true,songNow:()=>.9});assert.ok(hub.sent.some(x=>x.data[0]===0xf2));assert.ok(hub.sent.some(x=>x.data[0]===0xfb));assert.ok(!hub.sent.some(x=>x.data[0]===0xfa));e.stop();});
test('stop clears queues, sends stop, and panics touched channels',()=>{const hub=new Hub(),settings=H.defaultSettings();Object.assign(settings.clock,{transport:true,outputKey:'acme|synth#1'});Object.assign(settings.players.keys,{outputKey:'acme|synth#1',guide:true,channel:2});const e=new H.Engine({hub,settings,now:()=>100});e.start({song,players:[player('keys')],speed:1,seek:0,end:2,songNow:()=>-.1});e.stop();assert.ok(hub.cleared.includes('out1'));assert.ok(hub.sent.some(x=>x.data[0]===0xfc));assert.ok(hub.panics.some(x=>x.id==='out1'&&x.channels.includes(2)));});
test('disconnected saved key fails safely via status callback',()=>{const hub=new Hub(),messages=[],settings=H.defaultSettings();const e=new H.Engine({hub,settings,onStatus:m=>messages.push(m)});assert.equal(e.sendKey('missing',[0xf8]),false);assert.equal(messages.length,1);});

test('explicit panic targets every connected output and all channels',()=>{const hub=new Hub(),e=new H.Engine({hub,settings:H.defaultSettings()});assert.equal(e.panic(true),2);assert.equal(hub.panics.length,2);assert.equal(hub.panics[0].channels.length,16);});

test('clock plan follows changing beat intervals',()=>{const s={bpm:120,duration:2.4,beats:[{time:0},{time:.5},{time:1.1},{time:1.7},{time:2.3}]};const plan=H.clockPlan(s,0,1.7);assert.ok(plan.includes(0));const first=plan[1]-plan[0],after=plan[25]-plan[24];assert.ok(Math.abs(first-.5/24)<1e-9);assert.ok(Math.abs(after-.6/24)<1e-9);});
test('song position pointer uses quarter-note beat grid',()=>{const s={bpm:120,beats:[{time:0},{time:.5},{time:1.1},{time:1.7}]};assert.equal(H.songPosition(s,1.1),8);assert.equal(H.songPosition(s,.25),2);});
