'use strict';
const test=require('node:test'), assert=require('node:assert/strict');
const {detectPitch,noteAt,level,AudioInputHub,messageFor}=require('../src/input.js');
const wave=(hz,rate=48000,amplitude=.2,dc=0)=>Float32Array.from({length:8192},(_,i)=>dc+amplitude*(Math.sin(2*Math.PI*hz*i/rate)+.35*Math.sin(4*Math.PI*hz*i/rate)));
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function harness({channels=2,delay=false,unknown=false}={}) {
 const tracks=[],calls=[],nodes=[],events=new Map();let release;
 const ctx={sampleRate:48000,destination:{},createMediaStreamSource:()=>node(),createChannelSplitter:n=>{const x=node();x.channels=n;return x;},createGain:()=>{const x=node();x.gain={value:1};return x;},createAnalyser:()=>{const x=node();x.getFloatTimeDomainData=a=>a.set(wave(110));return x;}};
 function node(){const n={connections:[],disconnected:false,connect(...args){this.connections.push(args);},disconnect(){this.disconnected=true;}};nodes.push(n);return n;}
 function stream(){const t={readyState:'live',label:'Virtual test interface',stop(){this.readyState='ended';this.stops=(this.stops||0)+1;},getSettings:()=>({...(unknown?{}:{channelCount:channels}),sampleRate:48000,deviceId:'private-id',groupId:'private-group',echoCancellation:false}),addEventListener:(n,f)=>events.set(t,f),removeEventListener:()=>events.delete(t)};tracks.push(t);return {getTracks:()=>[t],getAudioTracks:()=>[t]};}
 const media={enumerateDevices:async()=>[{kind:'audioinput',deviceId:'default',label:'Default'},{kind:'audioinput',deviceId:'interface',label:'Virtual test interface'}],getUserMedia:async c=>{calls.push(c);if(delay)await new Promise(r=>release=r);return stream();},addEventListener(){},removeEventListener(){}};
 const states=[],data=[];
 const hub=new AudioInputHub({getContext:async()=>ctx,mediaDevices:media,onState:(r,s)=>states.push([r,s]),onData:(r,d)=>data.push([r,d])});
 return {hub,ctx,tracks,calls,nodes,events,states,data,resolve:()=>release?.()};
}
test('reference note conversion and invalid frequencies',()=>{assert.equal(noteAt(440).name,'A4');assert.equal(noteAt(440).cents,0);assert.equal(noteAt(0),null);assert.equal(noteAt(NaN),null);});
test('silence and DC are not interpreted as notes',()=>{assert.equal(detectPitch(new Float32Array(8192),48000),null);assert.equal(detectPitch(new Float32Array(8192).fill(.5),48000),null);});
test('guitar and low bass fundamentals survive harmonics at 44.1/48/96 kHz',()=>{for(const rate of [44100,48000,96000])for(const f of [30.8677,41.2034,55,82.4069,110,220,440,659.255]){const p=detectPitch(wave(f,rate),rate);assert.ok(p,`${f} at ${rate}`);assert.ok(Math.abs(1200*Math.log2(p.frequency/f))<7,`${f}: ${p.frequency}`);}});
test('noise gate rejects quiet samples and can be lowered',()=>{const x=wave(110,48000,.0003);assert.equal(detectPitch(x,48000),null);assert.equal(detectPitch(x,48000,{gateDb:-80}).name,'A2');});
test('DC offset does not bias pitch estimation',()=>{const p=detectPitch(wave(220,48000,.2,.3),48000);assert.ok(Math.abs(p.frequency-220)<1);});
test('unpitched deterministic noise does not produce a tuner note',()=>{let seed=19;const x=Float32Array.from({length:8192},()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return ((seed>>>0)/4294967296-.5)*.4;});assert.equal(detectPitch(x,48000),null);});
test('invalid sample buffers and rates are rejected',()=>{assert.equal(detectPitch([],48000),null);assert.equal(detectPitch(wave(220),0),null);const x=wave(220);x[5]=NaN;assert.equal(detectPitch(x,48000),null);});
test('level meter reports amplitude and peak independently',()=>{const x=wave(110);const m=level(x);assert.ok(m.db<-10&&m.db>-30);assert.ok(m.peak>.2);assert.equal(level(new Float32Array([1,-1])).peak,1);});
test('permission discovery stops its temporary capture and removes default aliases',async()=>{const h=harness();try{const d=await h.hub.allow();assert.equal(d.length,1);assert.equal(d[0].name,'Virtual test interface');assert.equal(h.tracks[0].readyState,'ended');assert.equal(h.calls[0].video,false);}finally{h.hub.destroy();}});
test('capture selects exact device, requests stereo and disables speech processing',async()=>{const h=harness();try{await h.hub.start('guitar','interface');const c=h.calls[0];assert.equal(c.audio.deviceId.exact,'interface');assert.equal(c.audio.channelCount.ideal,2);assert.equal(c.audio.echoCancellation,false);assert.equal(c.audio.noiseSuppression,false);assert.equal(c.audio.autoGainControl,false);assert.equal(c.video,false);assert.ok(h.nodes.some(n=>n.gain?.value===0));}finally{h.hub.destroy();}});
test('guitar and bass share one stream but get distinct splitter channels',async()=>{const h=harness();try{await Promise.all([h.hub.start('guitar','interface',1),h.hub.start('bass','interface',2)]);assert.equal(h.calls.length,1);assert.equal(h.hub.routes.size,2);const splitter=h.hub.routes.get('guitar').entry.splitter;assert.deepEqual(splitter.connections.map(c=>c[1]),[0,1]);h.hub.stop('guitar');assert.equal(h.tracks[0].readyState,'live');h.hub.stop('bass');assert.equal(h.tracks[0].readyState,'ended');assert.equal(h.hub.entries.size,0);}finally{h.hub.destroy();}});
test('mono input cannot silently masquerade as channel two',async()=>{const h=harness({channels:1});try{await assert.rejects(h.hub.start('bass','interface',2),/exposes 1 browser channel/);assert.equal(h.hub.routes.size,0);assert.equal(h.tracks[0].readyState,'ended');assert.equal(h.hub.entries.size,0);}finally{h.hub.destroy();}});
test('unknown channel count is reported as unknown, not confirmed stereo',async()=>{const h=harness({unknown:true});try{await h.hub.start('guitar','interface',2);assert.equal(h.hub.describe('guitar').channels,null);}finally{h.hub.destroy();}});
test('cancelling an in-flight permission request releases its late stream',async()=>{const h=harness({delay:true});try{const p=h.hub.start('guitar','interface',1);await tick();h.hub.stopAll();h.resolve();assert.equal(await p,null);assert.equal(h.tracks[0].readyState,'ended');assert.equal(h.hub.routes.size,0);assert.equal(h.hub.entries.size,0);}finally{h.hub.destroy();}});
test('ended capture cleans all shared routes and their timer',async()=>{const h=harness();try{await h.hub.start('guitar','interface',1);await h.hub.start('bass','interface',2);h.events.get(h.tracks[0])();assert.equal(h.hub.routes.size,0);assert.equal(h.hub.timer,null);assert.ok(h.states.some(([r,s])=>r==='bass'&&s.error));}finally{h.hub.destroy();}});
test('live analyser samples feed meters and tuner without a score callback',async()=>{const h=harness();try{await h.hub.start('guitar','interface');h.hub.sample();assert.equal(h.data[0][1].pitch.name,'A2');assert.ok(h.data[0][1].signal);assert.equal(h.data[0][1].score,undefined);}finally{h.hub.destroy();}});
test('diagnostics strip device and group IDs',async()=>{const h=harness();try{await h.hub.start('guitar','interface');const text=JSON.stringify(h.hub.describe('guitar'));assert.ok(!text.includes('private-id'));assert.ok(!text.includes('private-group'));assert.ok(!text.includes('deviceId'));}finally{h.hub.destroy();}});
test('permission, driver and unavailable-device failures have actionable messages',()=>{for(const name of ['NotAllowedError','NotFoundError','NotReadableError','OverconstrainedError'])assert.ok(messageFor({name}).length>50);});
test('missing device and invalid channels never invoke capture',async()=>{const h=harness();try{await assert.rejects(h.hub.start('guitar',''),/Choose an audio input/);await assert.rejects(h.hub.start('bass','interface',0),/valid browser channel/);assert.equal(h.calls.length,0);}finally{h.hub.destroy();}});

test('cancelling discovery before permission resolves stops its late stream',async()=>{const h=harness({delay:true});try{const p=h.hub.allow();await tick();h.hub.stopAll();h.resolve();assert.deepEqual(await p,[]);assert.equal(h.tracks[0].readyState,'ended');assert.equal(h.hub.discoveryStreams.size,0);}finally{h.hub.destroy();}});
test('stop-all terminates discovery even while enumeration is pending',async()=>{const h=harness();let done;h.hub.media.enumerateDevices=()=>new Promise(r=>done=r);try{const p=h.hub.allow();await tick();assert.equal(h.tracks[0].readyState,'live');h.hub.stopAll();assert.equal(h.tracks[0].readyState,'ended');done([]);assert.deepEqual(await p,[]);assert.equal(h.hub.discoveryStreams.size,0);}finally{h.hub.destroy();}});
