const test=require('node:test');const assert=require('node:assert/strict');const O=require('../src/onboarding.js');const H=require('../src/hardware.js');
const devices=[{id:'kit-id',name:'Virtual Drum Kit',manufacturer:'Test'},{id:'keys-id',name:'Virtual Keys',manufacturer:'Test'}];
const outputs=[{id:'synth-id',key:'test|virtual synth#1',name:'Virtual Synth',manufacturer:'Test'}];
function player(id,extra={}){return {id,input:'midi',device:'any',channel:0,offsetMs:0,...extra};}
test('device-name role suggestions are conservative and useful',()=>{assert.equal(O.suggestRole('Alesis Nitro Mesh Kit'),'drums');assert.equal(O.suggestRole('Launchkey 61'),'keys');assert.equal(O.suggestRole('USB Audio'),'');});
test('unassigned MIDI role asks to be identified',()=>assert.deepEqual(O.inputStatus(player('drums'),devices,{}),{state:'needs',label:'Play it to identify'}));
test('connected MIDI assignment reports device and channel',()=>assert.deepEqual(O.inputStatus(player('drums',{device:'kit-id',channel:10}),devices,{}),{state:'ready',label:'Virtual Drum Kit · ch 10'}));
test('disconnected saved MIDI assignment is explicit',()=>assert.equal(O.inputStatus(player('keys',{device:'gone',channel:1}),devices,{}).state,'missing'));
test('audio role requires a selected soundcheck device',()=>{assert.equal(O.inputStatus(player('guitar',{input:'audio'}),devices,{}).state,'needs');assert.equal(O.inputStatus(player('guitar',{input:'audio'}),devices,{guitar:{device:'iface'}}).state,'ready');});
test('per-player calibration subtracts global correction and clamps',()=>{assert.equal(O.playerOffset(42,12),30);assert.equal(O.playerOffset(900,0),500);assert.equal(O.playerOffset(-900,0),-500);});
test('hardware report excludes raw browser device ids',()=>{const hw=H.defaultSettings();hw.players.keys.outputKey=outputs[0].key;hw.players.keys.preset='synth';hw.players.keys.guide=true;const r=O.profileReport({players:[player('drums',{device:'kit-id',channel:10}),player('keys',{device:'keys-id',channel:1}),player('guitar',{input:'audio'}),player('bass')],devices,outputs,hardware:hw,audioSettings:{guitar:{device:'opaque-audio-id',deviceName:'USB Interface',channel:1}},createdAt:'2026-09-08T00:00:00Z'});const text=JSON.stringify(r);assert.equal(text.includes('kit-id'),false);assert.equal(text.includes('keys-id'),false);assert.equal(text.includes('opaque-audio-id'),false);assert.equal(r.players.keys.output.name,'Virtual Synth');});
test('report retains useful role/channel/correction information',()=>{const r=O.profileReport({players:[player('drums',{device:'kit-id',channel:10,offsetMs:17}),player('keys'),player('guitar'),player('bass')],devices,outputs,globalOffset:4});assert.equal(r.globalCorrectionMs,4);assert.equal(r.players.drums.midiChannel,10);assert.equal(r.players.drums.correctionMs,17);assert.equal(r.players.drums.inputPort.name,'Virtual Drum Kit');});
test('clock report resolves stable output signature to readable label',()=>{const hw=H.defaultSettings();hw.clock={enabled:true,transport:true,outputKey:outputs[0].key};const r=O.profileReport({players:O.ROLES.map(id=>player(id)),devices,outputs,hardware:hw});assert.equal(r.clock.enabled,true);assert.equal(r.clock.output.name,'Virtual Synth');});
test('report has explicit physical-validation limitations',()=>{const r=O.profileReport({players:O.ROLES.map(id=>player(id))});assert.ok(r.limitations.some(x=>/not certified/i.test(x)));});
