"""Quick MP3 -> rhythm highway tests. Actual MP3 decoding, Worker, playback and
capture graphs; synthetic audio and MIDI, simulated IndexedDB/permissions.
No user hardware or source song files are accessed.
"""
from pathlib import Path
import json, os, re, shutil
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'MIDI-Stage.html').read_text()
def mock(name): return re.search(r'MOCK\s*=\s*r"""(.*?)"""',(ROOT/'tests'/name).read_text(),re.S).group(1)
MOCK=mock('workshop.browser.py')+mock('strings.browser.py')
checks=[]
def check(name,value):
    if not value: raise AssertionError(name)
    checks.append(name);print('PASS',name,flush=True)
def ws(page):return page.evaluate('MIDIStage.getWorkshopSnapshot()')
def game(page):return page.evaluate('MIDIStage.getSnapshot()')
def ready(page):page.wait_for_function('!MIDIStage.getWorkshopSnapshot().busy')
def count(page):return sum(len(x['notes']) for x in ws(page)['project']['parts'])
def import_pulse(page):
    page.locator('#wsFile').set_input_files(str(ROOT/'tests/fixtures/quick-import-pulse.mp3'));ready(page)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium') or shutil.which('google-chrome'),headless=True,args=['--no-sandbox','--autoplay-policy=no-user-gesture-required'])
    ctx=b.new_context(viewport={'width':1440,'height':1120});ctx.add_init_script(MOCK)
    page=ctx.new_page();errors=[];requests=[];accept={'yes':True}
    page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
    page.on('dialog',lambda d:d.accept() if accept['yes'] else d.dismiss())
    page.set_content(HTML,wait_until='load');page.locator('#openWorkshop').click()
    check('quick import defaults to automatic generation with advanced editor collapsed',page.locator('#wsAuto').is_checked() and not page.locator('#wsAdvanced').evaluate('(e)=>e.open'))
    page.evaluate('window.__analysisRuns=0; const run=StageSongAnalysis.Job.prototype.run;StageSongAnalysis.Job.prototype.run=function(...a){__analysisRuns++;return run.apply(this,a);};void 0;')
    page.evaluate("window.__resume=AudioContext.prototype.resume;window.__resumeCalls=0;Object.defineProperty(AudioContext.prototype,'state',{configurable:true,get:()=> 'suspended'});AudioContext.prototype.resume=function(){__resumeCalls++;return new Promise(()=>{});};void 0;")
    page.locator('#wsFullBand').click();import_pulse(page)
    check('import decoding never waits on blocked autoplay resume',page.evaluate('__resumeCalls')==0)
    page.evaluate('AudioContext.prototype.resume=__resume;delete AudioContext.prototype.state;void 0;')
    check('real MP3 import automatically creates four playable rhythm highways',all(x['notes'] for x in ws(page)['project']['parts']) and ws(page)['project']['matching']=='rhythm')
    check('automatic pulse estimate and first-beat alignment match synthetic reference',abs(ws(page)['analysis']['bpm']-120)<1 and abs(ws(page)['project']['firstBeat']-.35)<.04)
    check('pulse analysis runs inside a real browser Worker',ws(page)['analysis']['backend']=='worker')
    check('normal import never opens microphone capture',page.evaluate('__audioMock.calls.length')==0)
    check('quick summary labels rhythm-only rather than exact song notes','Rhythm only' in page.locator('#wsQuickReady').inner_text() and page.locator('#wsQuickPlay').is_enabled())
    check('advanced controls are not needed after MP3 import',not page.locator('#wsAdvanced').evaluate('(e)=>e.open'))
    before_preview=page.locator('#wsQuickCanvas').evaluate('(e)=>e.toDataURL()')
    page.locator('#wsQuickPreview').click();ready(page);page.wait_for_timeout(150)
    check('one-click preview uses the actual audio transport',ws(page)['preview'])
    check('quick preview displays moving playhead and generated markers',before_preview!=page.locator('#wsQuickCanvas').evaluate('(e)=>e.toDataURL()') and 'Playing preview' in page.locator('#wsQuickWindow').inner_text())
    page.locator('#wsQuickStop').click();check('quick preview can stop without losing the chart',not ws(page)['preview'] and count(page)>0)
    original=count(page);page.locator('#wsQuickDensity').select_option('easy');page.locator('#wsQuickRebuild').click();ready(page)
    check('easier chart lowers marker count without decoding or analyzing again',0<count(page)<original and page.evaluate('__analysisRuns')==1)
    page.locator('#wsQuickDensity').select_option('medium');page.locator('#wsQuickRebuild').click();ready(page)
    bpm=ws(page)['project']['bpm'];page.locator('#wsHalfTempo').click();ready(page)
    check('half-tempo correction is immediately applied',abs(ws(page)['project']['bpm']-bpm/2)<.02)
    page.locator('#wsDoubleTempo').click();ready(page)
    check('double-tempo correction restores the original pulse',abs(ws(page)['project']['bpm']-bpm)<.02)
    with page.expect_download() as dl:page.locator('#wsExport').click()
    exported=Path(dl.value.path()).read_text();chart=json.loads(exported)
    check('portable export keeps explicit rhythm matching without audio bytes',chart['version']==2 and chart['matching']=='rhythm' and 'blob' not in chart)
    # Route physical-input simulations before exercising the one-button start.
    page.locator('#wsPlay').click();page.locator('#connectMIDI').click()
    for role,dev in [('drums','kit'),('keys','keys')]:
        page.locator(f'[data-route="device"][data-player="{role}"]').select_option(dev)
        page.locator(f'[data-route="channel"][data-player="{role}"]').select_option('0')
    for role in ['guitar','bass']:page.locator(f'[data-route="input"][data-player="{role}"]').select_option('audio')
    page.locator('[data-close="setupDialog"]').last.click()
    page.locator('#openSoundcheck').click();page.locator('#soundAllow').click()
    for role,ch in [('guitar','1'),('bass','2')]:
        page.locator(f'#{role}AudioDevice').select_option('duo');page.locator(f'#{role}AudioChannel').select_option(ch)
    page.locator('#soundClose').click();page.locator('#openWorkshop').click();page.locator('#wsQuickPlay').click()
    page.wait_for_function("MIDIStage.getSnapshot().status==='playing'")
    check('Play now saves and starts directly without a second Start click',not ws(page)['open'] and game(page)['rhythmOnly'] and page.locator('.ws-library-row').count()==1)
    check('all four gameplay judges use rhythm matching for this chart',all(x['matching']=='rhythm' for x in game(page)['players']))
    first=game(page)['players'][0]['notes'][0]['time']
    page.evaluate(f"__at({first},()=>{{__send('kit',[0x90,77,110]);__send('keys',[0x90,81,100]);__audioMock.pluck(1,52,1.3);__audioMock.pluck(2,40,1.3);}})")
    page.wait_for_timeout(250)
    check('real audio graphs and MIDI score non-placeholder pitches on all four parts',all(x['stats']['perfect']+x['stats']['great']+x['stats']['good']==1 for x in game(page)['players']))
    check('live audio feedback says any note, not invented fret positions','Any clean single note' in page.locator('#liveInputs').inner_text() and 'Rhythm only' in page.locator('#liveInputs').inner_text())
    page.evaluate(f'__at({first+1.1},()=>{{}})')
    check('one ringing audio note cannot repeatedly score later markers',all(x['stats']['perfect']+x['stats']['great']+x['stats']['good']==1 for x in game(page)['players'][2:]))
    page.locator('#pause').click();check('pausing rhythm gameplay releases audio capture',not game(page)['audio']['running'] and page.evaluate('__audioMock.live().length')==0)
    page.locator('#openWorkshop').click()
    page.locator('#wsFile').set_input_files({'name':'rhythm.midistage.json','mimeType':'application/json','buffer':exported.encode()});ready(page)
    check('rhythm chart reimport preserves matching and requires source audio',ws(page)['project']['matching']=='rhythm' and 'Reattach' in page.locator('#wsAudioName').inner_text())
    page.locator('#wsAudioFile').set_input_files(str(ROOT/'tests/fixtures/quick-import-pulse.mp3'));ready(page)
    check('reattaching source audio preserves authored markers',ws(page)['project']['parts']==chart['parts'])
    pitch_chart={**chart,'version':1,'origin':'manual'};pitch_chart.pop('matching')
    page.locator('#wsFile').set_input_files({'name':'pitch.midistage.json','mimeType':'application/json','buffer':json.dumps(pitch_chart).encode()});ready(page)
    page.locator('#wsAudioFile').set_input_files(str(ROOT/'tests/fixtures/quick-import-pulse.mp3'));ready(page)
    check('backing-audio attachment never labels an exact-note chart as rhythm-only','retains note-pitch' in page.locator('#wsQuickScope').inner_text() and 'matching' not in ws(page)['project'])
    # Worker-blocked environments still get a chart.
    page.evaluate('window.__nativeWorker=Worker;window.Worker=class {constructor(){throw Error("Test worker blocked");}};void 0;')
    import_pulse(page)
    check('blocked Worker falls back to local analysis without losing import',ws(page)['analysis']['backend']=='cooperative' and count(page)>0)
    page.evaluate('window.Worker=__nativeWorker;void 0;')
    page.locator('#wsFile').set_input_files(str(ROOT/'tests/fixtures/workshop-tone.mp3'));ready(page)
    check('uncertain short audio never silently invents a tempo or playable transcription',ws(page)['analysis']['bpm'] is None and count(page)==0 and page.locator('#wsQuickPlay').is_disabled())
    page.locator('#wsQuickTempo').fill('120');page.locator('#wsQuickRebuild').click();ready(page)
    check('manual-tempo fallback makes an explicitly rhythm-only playable chart',count(page)>0 and ws(page)['project']['matching']=='rhythm')
    prior=ws(page)['project']
    # Delay one decode; cancel; allow a new import; resolve the old promise LAST.
    page.evaluate('''window.__decode=AudioContext.prototype.decodeAudioData;
      AudioContext.prototype.decodeAudioData=function(...args){AudioContext.prototype.decodeAudioData=__decode;return new Promise(resolve=>{window.__finishOld=()=>__decode.apply(this,args).then(resolve);});};void 0;''')
    import_path=str(ROOT/'tests/fixtures/quick-import-pulse.mp3')
    page.locator('#wsFile').set_input_files(import_path);page.wait_for_function('!!window.__finishOld');page.locator('#wsCancelAnalysis').click()
    check('cancel during decode immediately restores editing and keeps previous chart',not ws(page)['busy'] and ws(page)['project']==prior)
    import_pulse(page);current=ws(page)['project'];page.evaluate('__finishOld();void 0');page.wait_for_timeout(300)
    check('late cancelled decode cannot overwrite a newer completed import',ws(page)['project']==current)
    page.evaluate('window.__terminations=0;window.Worker=class {postMessage(){}terminate(){__terminations++;}};void 0;')
    page.locator('#wsFile').set_input_files(import_path);page.wait_for_function('document.querySelector("#wsProgress").value>=75');page.locator('#wsCancelAnalysis').click();ready(page)
    check('cancelling analysis terminates its worker and retains the chart',page.evaluate('__terminations')>=1 and ws(page)['project']==current)
    page.evaluate('window.Worker=__nativeWorker;void 0;')
    page.locator('#wsFile').set_input_files({'name':'broken.mp3','mimeType':'audio/mpeg','buffer':b'not mp3'});ready(page)
    check('invalid audio fails without destroying the previous arrangement',ws(page)['project']==current and 'could not be decoded' in page.locator('#wsStatus').inner_text() and not page.locator('#wsAnalysisProgress').is_visible())
    # Destructive regeneration must ask before overwriting hand edits.
    page.locator('#wsAdvanced').evaluate('(e)=>e.open=true');page.locator('#wsNoteTime').fill('0.2');page.locator('#wsAdd').click();edited=ws(page)['project'];accept['yes']=False
    page.locator('#wsQuickRebuild').click();ready(page)
    check('declining regeneration protects manually edited notes',ws(page)['project']==edited)
    accept['yes']=True;import_pulse(page)
    page.evaluate("document.querySelector('#workshopDialog .eyebrow').textContent='SONG WORKSHOP / SYNTHETIC MP3 TEST';")
    out=Path(os.environ.get('TEST_ARTIFACT_DIR','/tmp/midi-stage-smart-import-tests'));out.mkdir(parents=True,exist_ok=True)
    page.locator('#workshopDialog').evaluate('(e)=>e.scrollTop=0');page.screenshot(path=str(out/'smart-import-desktop-TEST.png'),full_page=True)
    page.set_viewport_size({'width':390,'height':844});page.locator('#workshopDialog').evaluate('(e)=>e.scrollTop=0')
    check('compact import layout fits a narrow screen without horizontal overflow',page.evaluate('document.querySelector("#workshopDialog").scrollWidth<=document.querySelector("#workshopDialog").clientWidth+2'))
    page.screenshot(path=str(out/'smart-import-mobile-TEST.png'),full_page=True);page.set_viewport_size({'width':1440,'height':1120})
    # Save failure cannot lock the user out of playing; a warning is visible in game.
    page.evaluate('__storageFailure=true');page.locator('#wsQuickPlay').click();page.wait_for_function("MIDIStage.getSnapshot().status==='playing'")
    check('storage failure still permits playback with an explicit unsaved warning','without a saved library copy' in page.locator('#toast').inner_text())
    page.locator('#pause').click()
    check('analysis sends no external network requests',not [u for u in requests if u.startswith(('http://','https://'))])
    check('no JavaScript page errors across quick-import workflows',not errors)
    b.close()
print(json.dumps({'checks':len(checks),'passed':checks,'javascript_errors':errors,'scope':'real MP3 decode/Worker/audio graph; simulated MIDI/devices/storage'},indent=2))
