'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const S=require('../src/strings.js'),C=require('../src/core.js'),I=require('../src/input.js');
const sample=(time,pitch=40,extras={})=>({timestamp:time,db:-20,windowMs:40,pitch:pitch===null?null:{midi:pitch,cents:0,confidence:.99},...extras});
const quiet=time=>sample(time,null,{db:-100});
function phrase(tracker,start,end,pitch=40,extras={}){const out=[];for(let t=start;t<=end;t+=20)out.push(...tracker.feed(sample(t,pitch,extras)));return out;}
const kinds=(events,kind)=>events.filter(e=>e.kind===kind);
const livePlayers=()=>C.defaults().map(p=>({...p,enabled:true,input:['guitar','bass'].includes(p.type)?'audio':'midi'}));
const routes={guitar:{device:'duo',channel:1,gateDb:-55},bass:{device:'duo',channel:2,gateDb:-55}};
const makeJudge=(notes,opts={})=>new C.Judge({lanes:[{pc:4},{pc:7},{pc:9},{pc:11}],notes:notes.map(n=>({lane:0,pitch:40,duration:.4,...n}))},{mode:'exact',verifiedHolds:true,...opts});
function apply(j,events){for(const e of events){const t=e.timestamp/1000,token=e.token;if(e.kind==='on')j.hit(t,{lane:j.lanes.findIndex(l=>l.pc===C.pc(e.pitch)),pitch:e.pitch,token});else if(e.kind==='off')j.release(token,t);else j.confirm(token,t);}}
test('held tone generates one onset, never a stream of repeat hits',()=>{const t=new S.NoteTracker(),out=phrase(t,1000,4000);assert.equal(kinds(out,'on').length,1);assert.equal(kinds(out,'on')[0].timestamp,1000);assert.ok(kinds(out,'hold').length>100);});
test('fresh plucks separated by silence retrigger the same pitch',()=>{const t=new S.NoteTracker();let out=phrase(t,0,300);for(let ms=320;ms<=460;ms+=20)out.push(...t.feed(quiet(ms)));out.push(...phrase(t,480,800));assert.equal(kinds(out,'on').length,2);assert.equal(kinds(out,'off').length,1);assert.notEqual(kinds(out,'on')[0].token,kinds(out,'on')[1].token);});
test('a new amplitude attack retriggers a ringing note only once',()=>{const t=new S.NoteTracker();const out=[...phrase(t,0,300,40,{db:-34}),...phrase(t,320,600,40,{db:-20})];assert.equal(kinds(out,'on').length,2);assert.equal(kinds(out,'off').length,1);});
test('stable pitch changes work without a silent gap (legato)',()=>{const t=new S.NoteTracker(),out=[...phrase(t,0,300),...phrase(t,320,620,43)];assert.deepEqual(kinds(out,'on').map(e=>e.pitch),[40,43]);assert.equal(kinds(out,'off')[0].timestamp,320);});
test('brief pitch glitches are not note attacks',()=>{const t=new S.NoteTracker();const out=[...phrase(t,0,200),...t.feed(sample(220,52)),...phrase(t,240,400)];assert.equal(kinds(out,'on').length,1);assert.equal(kinds(out,'off').length,0);});
test('low confidence, cents outside tolerance, clipping and mute cannot attack',()=>{for(const extras of [{pitch:{midi:40,cents:0,confidence:.5}},{pitch:{midi:40,cents:46,confidence:1}},{clipping:true},{muted:true}]){const t=new S.NoteTracker();assert.equal(kinds(phrase(t,0,500,40,extras),'on').length,0);}});
test('sustained unpitched noise cannot turn into a delayed free attack',()=>{const t=new S.NoteTracker();phrase(t,0,600,null);assert.equal(kinds(phrase(t,620,1000),'on').length,0);});
test('expired onset is discarded rather than awarded very late',()=>{const t=new S.NoteTracker();phrase(t,0,260,null);assert.equal(kinds(phrase(t,280,700),'on').length,0);});
test('analysis window must clear before retrigger pitch is trusted',()=>{const t=new S.NoteTracker();phrase(t,0,300,40,{windowMs:86,db:-34});const early=phrase(t,320,360,40,{windowMs:86,db:-20}),late=phrase(t,380,540,43,{windowMs:86,db:-20});assert.equal(kinds(early,'on').length,0);assert.deepEqual(kinds(late,'on').map(e=>e.pitch),[43]);assert.equal(kinds(late,'on')[0].timestamp,320);});
test('silence releases at the beginning of the dropout, not after debounce',()=>{const t=new S.NoteTracker();phrase(t,0,300);let out=[];for(let ms=320;ms<=440;ms+=20)out.push(...t.feed(quiet(ms)));assert.equal(kinds(out,'off')[0].timestamp,320);});
test('brief confidence dropout tolerates jitter without a fake retrigger',()=>{const t=new S.NoteTracker();let out=phrase(t,0,200);out.push(...t.feed(sample(220,null)),...t.feed(sample(240,null)),...phrase(t,260,500));assert.equal(kinds(out,'on').length,1);assert.equal(kinds(out,'off').length,0);});
test('sustained uncertainty releases and recovery alone cannot re-score a ringing pitch',()=>{const t=new S.NoteTracker();let out=phrase(t,0,200);out.push(...phrase(t,220,400,null),...phrase(t,420,800));assert.equal(kinds(out,'on').length,1);assert.equal(kinds(out,'off').length,1);});
test('reordered or nonfinite timestamps are ignored',()=>{const t=new S.NoteTracker();phrase(t,0,200);for(const stamp of [200,180,NaN,Infinity])assert.deepEqual(t.feed(sample(stamp,43)),[]);});
test('reset clears ringing notes but never reuses an old token',()=>{const t=new S.NoteTracker(),a=kinds(phrase(t,0,200),'on')[0];t.reset();const b=kinds(phrase(t,0,200),'on')[0];assert.notEqual(a.token,b.token);});
test('audio exact-pitch scoring rejects an octave error',()=>{const j=makeJudge([{time:1}]),t=new S.NoteTracker();apply(j,phrase(t,1000,1200,52));assert.equal(j.stats.perfect,0);assert.equal(j.stats.extra,1);});
test('no chart-based pitch snapping: unrelated pitch counts as extra',()=>{const j=makeJudge([{time:1}]),t=new S.NoteTracker();apply(j,phrase(t,1000,1200,41));assert.equal(j.stats.extra,1);assert.equal(j.stats.score,0);});
test('a steady tone cannot score successive chart notes',()=>{const j=makeJudge([{time:1,duration:.1},{time:1.5,duration:.1}]),t=new S.NoteTracker();apply(j,phrase(t,1000,2000));j.tick(2);assert.equal(j.stats.perfect,1);assert.equal(j.stats.miss,1);});
test('audio holds need fresh confidence, not just passage of time',()=>{const j=makeJudge([{time:1,duration:1}]);j.hit(1,{lane:0,pitch:40,token:'a'});j.tick(3);assert.equal(j.stats.holds,0);j.release('a',3);assert.equal(j.stats.holdBreaks,1);});
test('valid matching pitch through the tail completes an audio sustain once',()=>{const j=makeJudge([{time:1,duration:1}]),t=new S.NoteTracker();apply(j,phrase(t,1000,2400));assert.equal(j.stats.holds,1);assert.equal(j.stats.score,150);assert.equal(j.stats.holdBreaks,0);});
test('stopping early breaks the hold despite a late note-off callback',()=>{const j=makeJudge([{time:1,duration:1}]),t=new S.NoteTracker();apply(j,phrase(t,1000,1400));for(let ms=1420;ms<=1600;ms+=20)apply(j,t.feed(quiet(ms)));j.tick(3);assert.equal(j.stats.holdBreaks,1);assert.equal(j.stats.holds,0);});
test('wrong-pitch transition cannot sustain the old note',()=>{const j=makeJudge([{time:1,duration:1}]),t=new S.NoteTracker();apply(j,phrase(t,1000,1400));apply(j,phrase(t,1420,2300,43));assert.equal(j.stats.holds,0);assert.equal(j.stats.holdBreaks,1);});
test('MIDI sustain behavior is unchanged when confidence verification is off',()=>{const j=makeJudge([{time:1,duration:1}],{verifiedHolds:false});j.hit(1,{lane:0,pitch:40,token:'a'});j.tick(2);assert.equal(j.stats.holds,1);});
test('audio confirmation does not accumulate unheld tokens',()=>{const j=makeJudge([{time:1,duration:.1}]);j.confirm('never-hit',5);assert.equal(j.confirmed.size,0);});
test('player corrections are independent, bounded, and additive to global correction',()=>{const players=livePlayers();players[2].offsetMs=75;players[3].offsetMs=-20;assert.equal(S.correctionMs(players[2],10),85);assert.equal(S.correctionMs(players[3],10),-10);assert.equal(S.correctionMs(players[0],10),10);assert.equal(S.correctionMs({offsetMs:Infinity}),500);});
test('correction uses wall-clock milliseconds at every practice speed',()=>{for(const speed of [.5,.75,1,1.25]){const j=makeJudge([{time:1,duration:.1}],{speed});const corrected=1+.085*speed-S.correctionMs({offsetMs:75},10)/1000*speed;j.hit(corrected,{lane:0,pitch:40});assert.equal(j.stats.perfect,1);}});
test('audio players never match MIDI device/channel routes',()=>{const p=livePlayers();assert.equal(C.routes(p[2],'duo',2),false);assert.deepEqual(C.routingConflicts(p),[]);});
test('same physical stream may use independent channels, never one shared channel',()=>{const p=livePlayers();assert.equal(S.routeError(p,routes),null);assert.match(S.routeError(p,{...routes,bass:routes.guitar}),/same audio channel/);});
test('missing devices are blocked before capture; disabled audio parts are ignored',()=>{const p=livePlayers();assert.match(S.routeError(p,{}),/soundcheck/);p[2].enabled=p[3].enabled=false;assert.equal(S.routeError(p,{}),null);});
test('monophonic validation song has all four parts and playable string charts',()=>{const s=C.makeValidationSong();assert.equal(s.duration,20);assert.equal(s.parts.length,4);for(const p of livePlayers()){const chart=C.makeChart(s,p);assert.ok(chart.notes.length>0);if(S.isAudio(p))assert.equal(S.chartError(chart.notes,p.id),null);}});
test('polyphonic and out-of-range string charts fail with an explanation',()=>{assert.match(S.chartError([{time:0,duration:1,pitch:40},{time:.1,duration:1,pitch:43}],'guitar'),/chords or overlapping/);assert.match(S.chartError([{time:0,duration:1,pitch:20}],'bass'),/range/);});
test('standard tuning hints are suggestions, including open strings and outside range',()=>{assert.equal(S.fretHint(40,'guitar'),'low E · open');assert.equal(S.fretHint(43,'guitar'),'low E · fret 3');assert.equal(S.fretHint(28,'bass'),'E · open');assert.match(S.fretHint(22,'bass'),/Outside/);});
test('short live windows recognize synthesized guitar and bass at three sample rates',()=>{for(const rate of [44100,48000,96000])for(const [role,f] of [['guitar',82.4069],['guitar',659.255],['bass',30.8677],['bass',41.2034]]){const n=S.frameSize(rate,role),data=Float32Array.from({length:n},(_,i)=>.2*(Math.sin(2*Math.PI*f*i/rate)+.25*Math.sin(4*Math.PI*f*i/rate)));const pitch=I.detectPitch(data,rate,{minHz:role==='bass'?28:65,maxHz:role==='bass'?550:1500});assert.ok(pitch,`${role} ${f} at ${rate}`);assert.ok(Math.abs(1200*Math.log2(pitch.frequency/f))<10);}});
class FakeHub {
  constructor(options){this.options=options;this.routes=new Map();this.pending=[];this.stops=0;}
  async start(role){if(this.delay)await new Promise(r=>this.pending.push(r));this.routes.set(role,{});return {active:true};}
  stopAll(){this.stops++;this.routes.clear();}
  destroy(){this.stopAll();}
}
test('live session forwards onsets and stops forwarding after stop',async()=>{const out=[],live=new S.LiveSession({InputHub:FakeHub,onEvent:(r,e)=>out.push([r,e])});await live.start(livePlayers(),routes);for(let t=0;t<=200;t+=20)live.receive('guitar',sample(t));assert.equal(out.filter(([,e])=>e.kind==='on').length,1);live.stop();const n=out.length;live.receive('guitar',sample(400));assert.equal(out.length,n);});
test('starting with duplicate channels never calls capture',async()=>{const live=new S.LiveSession({InputHub:FakeHub});await assert.rejects(live.start(livePlayers(),{...routes,bass:routes.guitar}),/same audio channel/);assert.equal(live.hub.routes.size,0);});
test('cancelled pending session cannot open the second player',async()=>{const live=new S.LiveSession({InputHub:FakeHub});live.hub.delay=true;const pending=live.start(livePlayers(),routes);live.stop();live.hub.pending.shift()();assert.equal(await pending,false);assert.equal(live.hub.pending.length,0);});
test('long analysis stalls request pause rather than backfilling scores',async()=>{const errors=[],live=new S.LiveSession({InputHub:FakeHub,onError:m=>errors.push(m)});await live.start(livePlayers(),routes);live.receive('guitar',sample(0));live.receive('guitar',sample(600));assert.equal(errors.length,1);assert.match(errors[0],/interrupted/);live.stop();});
test('malformed pitch confidence and out-of-MIDI-range observations are rejected',()=>{for(const pitch of [{midi:-1,cents:0,confidence:1},{midi:140,cents:0,confidence:1},{midi:40,cents:0,confidence:Infinity},{midi:40,cents:NaN,confidence:1}]){const t=new S.NoteTracker();assert.equal(kinds(phrase(t,0,500,40,{pitch}),'on').length,0);}});
