/* Guided hardware discovery, role assignment, calibration handoff and profile report. */
(function(root,factory){
  const api=factory(typeof module==='object'&&module.exports?require('./core.js'):root.StageCore,typeof module==='object'&&module.exports?require('./hardware.js'):root.StageHardware);
  if(typeof module==='object'&&module.exports)module.exports=api;else root.StageOnboarding=api;
})(globalThis,function(C,H){
  'use strict';
  const ROLES=['drums','keys','guitar','bass'],LABELS={drums:'Drums',keys:'Keyboard',guitar:'Guitar',bass:'Bass'};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function suggestRole(name=''){const s=String(name).toLowerCase();if(/drum|kit|percussion|alesis|roland td|nitro|strike/.test(s))return'drums';if(/piano|key|keyboard|keystation|keylab|launchkey|oxygen/.test(s))return'keys';if(/bass/.test(s))return'bass';if(/guitar|gt-|guitar wing/.test(s))return'guitar';return'';}
  function inputStatus(player,devices=[],audioSettings={}){if(player.input==='audio')return audioSettings?.[player.id]?.device?{state:'ready',label:'Audio input selected'}:{state:'needs',label:'Choose audio input'};if(player.device&&player.device!=='any'){const d=devices.find(x=>x.id===player.device);return d?{state:'ready',label:`${d.name} · ch ${player.channel||'any'}`}:{state:'missing',label:'Saved MIDI input disconnected'};}return {state:'needs',label:'Play it to identify'};}
  function playerOffset(measured,globalOffset=0){return clamp(Math.round((Number(measured)||0)-(Number(globalOffset)||0)),-500,500);}
  function cleanPort(port){return port?{name:String(port.name||''),manufacturer:String(port.manufacturer||'')}:null;}
  function profileReport({players=[],devices=[],outputs=[],hardware=H.defaultSettings(),audioSettings={},globalOffset=0,createdAt=new Date().toISOString()}={}){
    const h=H.normalizeSettings(hardware),findIn=id=>cleanPort(devices.find(d=>d.id===id)),findOut=key=>cleanPort(outputs.find(o=>o.key===key));
    return {app:'MIDI Stage',version:'0.8-hardware-profile',createdAt,purpose:'Local hardware routing and timing profile. No audio, browser device IDs or SysEx data are included.',globalCorrectionMs:globalOffset,players:Object.fromEntries(ROLES.map(role=>{const p=players.find(x=>x.id===role)||{id:role,input:'midi',device:'any',channel:0,offsetMs:0},hp=h.players[role],audio=audioSettings?.[role]||{};return [role,{input:p.input==='audio'?'audio':'midi',inputPort:p.input==='audio'?{name:audio.deviceName||'Selected browser audio input',browserChannel:audio.channel||1}:findIn(p.device),midiChannel:p.input==='audio'?null:(p.channel||0),correctionMs:Number(p.offsetMs)||0,output:findOut(hp.outputKey),outputChannel:hp.channel,outputProfile:hp.preset,guide:hp.guide,feedback:hp.feedback,feedbackNumber:hp.feedbackNumber}];})),clock:{enabled:h.clock.enabled,transport:h.clock.transport,output:findOut(h.clock.outputKey)},limitations:['Device labels may be generic.','Audio browser channels do not prove physical jack numbers.','Per-player timing calibration measures the played response to audible clicks; it is not independent hardware latency.','Physical compatibility is not certified until tested with the real device.']};
  }
  class Controller{
    constructor({getPlayers=()=>[],getDevices=()=>[],getOutputs=()=>[],getHardware=()=>H.defaultSettings(),getAudioSettings=()=>({}),getGlobalOffset=()=>0,isComplete=()=>false,connect=async()=>{},assignInput=()=>{},setInputMode=()=>{},setOutput=()=>{},setClock=()=>{},setOffset=()=>{},testOutput=()=>false,openSoundcheck=()=>{},calibrate=()=>{},finish=()=>{},panic=()=>{},onStatus=()=>{}}={}){
      Object.assign(this,{getPlayers,getDevices,getOutputs,getHardware,getAudioSettings,getGlobalOffset,isComplete,connect,assignInput,setInputMode,setOutput,setClock,setOffset,testOutput,openSoundcheck,calibrate,finish,panic,onStatus});this.step=0;this.listening='';this.busy=false;this.dialog=null;
    }
    mount(){this.dialog=document.getElementById('onboardingDialog');if(!this.dialog)return;document.getElementById('wizardClose').onclick=()=>this.close();document.getElementById('wizardBack').onclick=()=>this.go(this.step-1);document.getElementById('wizardNext').onclick=()=>this.step===4?this.complete():this.go(this.step+1);document.getElementById('wizardReport').onclick=()=>this.download();this.dialog.addEventListener('close',()=>{this.listening='';});}
    open(step=0){if(!this.dialog)this.mount();this.step=clamp(Math.round(Number(step)||0),0,4);this.listening='';this.render();if(!this.dialog.open)this.dialog.showModal();}
    close(){if(this.dialog?.open)this.dialog.close();}
    go(step){this.step=clamp(step,0,4);this.listening='';this.render();}
    receiveMIDI(event){if(!this.dialog?.open||this.step!==1||!this.listening||event.kind!=='on')return false;const role=this.listening;this.listening='';this.assignInput(role,event.device,event.channel);this.onStatus(`${LABELS[role]} identified from MIDI note ${event.note}, channel ${event.channel}.`);this.render();return true;}
    async doConnect(){if(this.busy)return;this.busy=true;this.render();try{await this.connect();this.onStatus('MIDI access ready. Play each instrument on the next step to identify it.');}catch(e){this.onStatus(e.message||'MIDI connection failed.');}finally{this.busy=false;this.render();}}
    context(){return {players:this.getPlayers(),devices:this.getDevices(),outputs:this.getOutputs(),hardware:H.normalizeSettings(this.getHardware()),audio:this.getAudioSettings(),globalOffset:this.getGlobalOffset()};}
    render(){if(!this.dialog)return;const c=this.context(),body=document.getElementById('wizardBody'),title=document.getElementById('wizardTitle'),eyebrow=document.getElementById('wizardEyebrow');document.getElementById('wizardBack').disabled=this.step===0;document.getElementById('wizardNext').textContent=this.step===4?'Save hardware profile':'Next';document.getElementById('wizardReport').hidden=this.step!==4;document.getElementById('wizardProgress').style.width=`${(this.step+1)/5*100}%`;eyebrow.textContent=`STEP ${this.step+1} / 5`;
      const renderPorts=list=>list.length?`<div class="wizard-port-list">${list.map(p=>`<span><b>${esc(p.name)}</b>${p.manufacturer?`<small>${esc(p.manufacturer)}</small>`:''}</span>`).join('')}</div>`:'<p class="wizard-empty">Nothing detected yet.</p>';
      if(this.step===0){title.textContent='Find your rig';body.innerHTML=`<p>Connect your MIDI drum kit, keyboard and any MIDI OUT hardware. Guitar/bass audio interfaces are handled in Audio soundcheck.</p><div class="wizard-counts"><div><strong>${c.devices.length}</strong><span>MIDI IN</span></div><div><strong>${c.outputs.length}</strong><span>MIDI OUT</span></div></div><h3>Inputs</h3>${renderPorts(c.devices)}<h3>Outputs</h3>${renderPorts(c.outputs)}<button id="wizardConnect" class="button primary">${this.busy?'Checking…':c.devices.length||c.outputs.length?'Refresh MIDI ports':'Connect & detect MIDI'}</button><small class="wizard-note">MIDI Stage requests normal MIDI access with SysEx disabled.</small>`;body.querySelector('#wizardConnect').onclick=()=>this.doConnect();}
      else if(this.step===1){title.textContent='Identify your instruments';body.innerHTML=`<p>Choose <b>Listen</b>, then hit one pad or key on that instrument. MIDI Stage will save the device and channel it actually receives.</p><div class="wizard-role-list">${ROLES.map(role=>{const p=c.players.find(x=>x.id===role),st=inputStatus(p,c.devices,c.audio),isAudio=p?.input==='audio';return `<section class="wizard-role ${st.state}"><div><strong>${LABELS[role]}</strong><span>${esc(st.label)}</span></div><div class="wizard-role-actions">${!isAudio?`<button class="button ${this.listening===role?'primary':'secondary'} small" data-listen="${role}">${this.listening===role?'Listening…':'Listen'}</button>`:''}${['guitar','bass'].includes(role)?`<button class="button ghost small" data-audio="${role}">${isAudio?'Audio selected':'Use audio interface'}</button>`:''}</div></section>`;}).join('')}</div><small class="wizard-note">If two instruments share one MIDI port, identifying each channel separately keeps them from cross-scoring.</small>`;body.querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>{this.listening=b.dataset.listen;this.render();});body.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>{this.setInputMode(b.dataset.audio,'audio');this.openSoundcheck(b.dataset.audio);});}
      else if(this.step===2){title.textContent='Set up MIDI OUT';const outputOptions=(selected='')=>`<option value="">No MIDI output</option>${c.outputs.map(o=>`<option value="${esc(o.key)}" ${selected===o.key?'selected':''}>${esc(o.name)}</option>`).join('')}`;body.innerHTML=`<p>Optional: route guide notes to an external synth, hit feedback to pads/LEDs, or both.</p><div class="wizard-output-list">${ROLES.map(role=>{const hp=c.hardware.players[role];return `<section><strong>${LABELS[role]}</strong><label>OUTPUT<select data-wout="${role}">${outputOptions(hp.outputKey)}</select></label><label>PROFILE<select data-wpreset="${role}"><option value="off" ${hp.preset==='off'?'selected':''}>Off</option><option value="synth" ${hp.preset==='synth'?'selected':''}>External synth</option><option value="feedback" ${hp.preset==='feedback'?'selected':''}>Pad / LED feedback</option><option value="hybrid" ${hp.preset==='hybrid'?'selected':''}>Hybrid</option><option value="custom" ${hp.preset==='custom'?'selected':''}>Custom</option></select></label><button class="button ghost small" data-wtest="${role}" ${hp.outputKey?'':'disabled'}>Test</button></section>`;}).join('')}</div><div class="wizard-clock"><label>CLOCK OUTPUT<select id="wizardClockOutput">${outputOptions(c.hardware.clock.outputKey)}</select></label><label class="check"><input id="wizardClock" type="checkbox" ${c.hardware.clock.enabled?'checked':''}> MIDI Clock · 24 PPQN</label><label class="check"><input id="wizardTransport" type="checkbox" ${c.hardware.clock.transport?'checked':''}> Start / Continue / Stop</label><button id="wizardPanic" class="button ghost small">PANIC / ALL NOTES OFF</button></div><small class="wizard-note">Generic Note/CC feedback may not light every controller. Device-specific LED presets require the real device model and MIDI implementation.</small>`;body.querySelectorAll('[data-wout]').forEach(el=>el.onchange=()=>{this.setOutput(el.dataset.wout,'outputKey',el.value);this.render();});body.querySelectorAll('[data-wpreset]').forEach(el=>el.onchange=()=>{this.setOutput(el.dataset.wpreset,'preset',el.value);this.render();});body.querySelectorAll('[data-wtest]').forEach(b=>b.onclick=()=>this.testOutput(b.dataset.wtest));body.querySelector('#wizardClockOutput').onchange=e=>this.setClock('outputKey',e.target.value);body.querySelector('#wizardClock').onchange=e=>this.setClock('enabled',e.target.checked);body.querySelector('#wizardTransport').onchange=e=>this.setClock('transport',e.target.checked);body.querySelector('#wizardPanic').onclick=()=>this.panic();}
      else if(this.step===3){title.textContent='Calibrate timing';body.innerHTML=`<p>Measure each MIDI player separately against audible clicks. Positive correction compensates a late response. Audio players use Soundcheck plus their manual player correction.</p><div class="wizard-cal-list">${ROLES.map(role=>{const p=c.players.find(x=>x.id===role),st=inputStatus(p,c.devices,c.audio),midi=p?.input!=='audio';return `<section><div><strong>${LABELS[role]}</strong><span>${esc(st.label)}</span></div><label>CORRECTION <input type="number" min="-500" max="500" step="1" value="${Number(p?.offsetMs)||0}" data-woffset="${role}"> ms</label>${midi?`<button class="button secondary small" data-wcal="${role}" ${st.state==='ready'?'':'disabled'}>Calibrate ${LABELS[role]}</button>`:`<button class="button secondary small" data-waudio="${role}">Open audio soundcheck</button>`}</section>`;}).join('')}</div><small class="wizard-note">Calibration includes your playing response and audio monitoring path. It is not a laboratory measurement of interface latency.</small>`;body.querySelectorAll('[data-woffset]').forEach(el=>el.onchange=()=>this.setOffset(el.dataset.woffset,clamp(Number(el.value)||0,-500,500)));body.querySelectorAll('[data-wcal]').forEach(b=>b.onclick=()=>this.calibrate(b.dataset.wcal));body.querySelectorAll('[data-waudio]').forEach(b=>b.onclick=()=>this.openSoundcheck(b.dataset.waudio));}
      else{title.textContent='Your rig is ready';const ready=ROLES.map(role=>{const p=c.players.find(x=>x.id===role),st=inputStatus(p,c.devices,c.audio),hp=c.hardware.players[role],out=hp.outputKey?c.outputs.find(o=>o.key===hp.outputKey)?.name||'Saved output':'Off';return `<section class="wizard-summary-row"><div><strong>${LABELS[role]}</strong><span>${esc(st.label)}</span></div><div><span>${Number(p?.offsetMs)||0} ms</span><small>MIDI OUT: ${esc(out)} · ${esc(hp.preset)}</small></div></section>`;}).join('');body.innerHTML=`<p>Review the routing below. Saving marks onboarding complete; you can rerun this wizard any time.</p><div class="wizard-summary">${ready}</div><p class="wizard-summary-clock">Clock: <b>${c.hardware.clock.enabled?(c.outputs.find(o=>o.key===c.hardware.clock.outputKey)?.name||'saved output'):'Off'}</b></p><small class="wizard-note">Physical compatibility and timing are only confirmed after you exercise the real devices. The saved report contains labels/settings, not audio or browser device IDs.</small>`;}
    }
    complete(){const report=profileReport({...this.context(),audioSettings:this.getAudioSettings()});this.finish(report);this.close();}
    report(){const c=this.context();return profileReport({...c,audioSettings:c.audio});}
    download(){const blob=new Blob([JSON.stringify(this.report(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MIDI-Stage-Hardware-Profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
    snapshot(){return {open:!!this.dialog?.open,step:this.step,listening:this.listening,busy:this.busy,complete:!!this.isComplete()};}
  }
  return {ROLES,LABELS,suggestRole,inputStatus,playerOffset,profileReport,Controller};
});
